services:
  - type: web
    name: paddleocr-web-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
